services:

  mariadb:
    image: mariadb:11.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - "db:/var/lib/mysql"

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfiles/nginx/Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION}"
    restart: always
    env_file: .env
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
      - "9443:443"
    volumes:
      - "./web:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"

  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfiles/php-fpm/Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION}"
    restart: always
    env_file: .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - "./web:/var/www/html"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    extra_hosts:
      - "${HTTP_HOST}:172.18.0.1"

  redis:
    image: redis:7.4-alpine
    restart: always
    expose:
      - "6379"
    # launch Redis in cache mode with:
    #  - max memory up to 50% of your RAM if needed (--maxmemory 512mb)
    #  - deleting the oldest data when max memory is reached (--maxmemory-policy allkeys-lru)
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --maxmemory 128mb
      - --maxmemory-policy allkeys-lru

volumes:
  db:
