version: '2'
services:
  mysql:
    image: mariadb:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  phpfpm:
    depends_on:
      - mysql
      - memcached
      - elasticsearch
    volumes:
      - "./site/web:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    restart: always
    build: ./dockerfiles/php-fpm
    extra_hosts:
      - "wp-docker-bedrock.dev:172.18.0.1"
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "8080:80"
    image: nginx:latest
    volumes:
      - "./site/web:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always
