name: PHP Security Checker

on:
  pull_request:

jobs:
  security-checker:
    name: PHP Security Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
          tools: composer:v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run composer install
        run: |
          composer install --no-interaction

      - uses: actions/cache@v6
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - uses: symfonycorp/security-checker-action@v5
